### ISSUE TITLE
Counts (empty) folders instead of just files

### ISSUE THREAD

**Issue by jrcalvert** [mwillman/PostChecker#1]
For example, if /var/spool/deferred countains 16 sub-folders but no actual deferred emails (no files) then PostChecker returns a count of 16 

In the "dircount" function, change to only count files, e.g. 
       # incr count if a file
      if (dp->d_type == 0x8 )
       {
                 count++;
       }

**Comment by mwillman** [comment]
Man, I haven't thought about this code in forever.  I've just updated master to include a patch that ignores anything that isn't in the spool directories that isn't a regular file.

Thanks for filing the issue!

-Matt

**Comment by jrcalvert** [comment]
No problem. First issue I've submitted!
